# Generated by Django 4.2.7 on 2025-08-24 06:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="limite_usuarios",
            field=models.IntegerField(default=5, verbose_name="Límite de usuarios"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="nombre_comercial",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nombre Comercial"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Razón Social"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="rfc",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="RFC inválido",
                        regex="^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$",
                    )
                ],
                verbose_name="RFC",
            ),
        ),
        migrations.CreateModel(
            name="UsuarioEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete: False indica registro eliminado",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Versión del registro"),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("PROPIETARIO", "Propietario"),
                            ("ADMINISTRADOR", "Administrador"),
                            ("CONTADOR", "Contador"),
                            ("AUXILIAR", "Auxiliar"),
                            ("CONSULTA", "Solo Consulta"),
                        ],
                        default="CONSULTA",
                        max_length=20,
                    ),
                ),
                (
                    "empresa_default",
                    models.BooleanField(
                        default=False, verbose_name="Empresa por defecto"
                    ),
                ),
                (
                    "ultimo_acceso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último acceso"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios_asignados",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Empresa",
                "verbose_name_plural": "Usuarios-Empresas",
                "ordering": ["empresa", "usuario"],
                "unique_together": {("usuario", "empresa")},
            },
        ),
    ]
