# Generated by Django 5.2.4 on 2025-08-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_options_empresa_limite_usuarios_and_more'),
    ]

    operations = [
    ]
