# Generated by Django 4.2.7 on 2025-08-24 07:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0002_alter_empresa_options_empresa_limite_usuarios_and_more"),
        ("catalogo_cuentas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransaccionContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete: False indica registro eliminado",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Versión del registro"),
                ),
                (
                    "folio",
                    models.CharField(
                        help_text="Número de póliza o transacción",
                        max_length=20,
                        verbose_name="Folio",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso"),
                            ("EGRESO", "Egreso"),
                            ("DIARIO", "Diario"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        default="DIARIO",
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        help_text="Descripción de la transacción",
                        max_length=500,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("VALIDADA", "Validada"),
                            ("CONTABILIZADA", "Contabilizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_contabilizacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Contabilización"
                    ),
                ),
                (
                    "total_debe",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total Debe",
                    ),
                ),
                (
                    "total_haber",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total Haber",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción Contable",
                "verbose_name_plural": "Transacciones Contables",
                "ordering": ["-fecha", "-folio"],
                "unique_together": {("empresa", "folio")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete: False indica registro eliminado",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Versión del registro"),
                ),
                (
                    "concepto",
                    models.CharField(
                        blank=True,
                        help_text="Concepto específico del movimiento (opcional)",
                        max_length=500,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "debe",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Debe",
                    ),
                ),
                (
                    "haber",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Haber",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="catalogo_cuentas.cuentacontable",
                        verbose_name="Cuenta Contable",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="transacciones.transaccioncontable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Contable",
                "verbose_name_plural": "Movimientos Contables",
                "ordering": ["id"],
            },
        ),
    ]
