# Generated by Django 5.2.4 on 2025-08-24 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20250824_1016'),
        ('transacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('codigo', models.CharField(help_text='Código único del tipo de transacción', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('prefijo', models.CharField(blank=True, help_text='Ej: ING-, EGR-, DIA-', max_length=10, verbose_name='Prefijo')),
                ('sufijo', models.CharField(blank=True, max_length=10, verbose_name='Sufijo')),
                ('longitud_numero', models.IntegerField(default=4, help_text='Número de dígitos para la numeración automática', verbose_name='Longitud del número')),
                ('ultimo_folio', models.IntegerField(default=0, verbose_name='Último folio utilizado')),
                ('requiere_validacion', models.BooleanField(default=True, help_text='Si requiere validación antes de contabilizar', verbose_name='Requiere validación')),
                ('permite_edicion', models.BooleanField(default=True, help_text='Si permite editar después de crear', verbose_name='Permite edición')),
                ('color_interfaz', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Morado'), ('red', 'Rojo'), ('yellow', 'Amarillo'), ('indigo', 'Índigo'), ('pink', 'Rosa'), ('gray', 'Gris')], default='blue', max_length=20, verbose_name='Color en interfaz')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_transaccion', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de Transacción',
                'verbose_name_plural': 'Tipos de Transacción',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='transaccioncontable',
            name='tipo_personalizado',
            field=models.ForeignKey(blank=True, help_text='Tipo de transacción personalizado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='transacciones.tipotransaccion', verbose_name='Tipo Personalizado'),
        ),
    ]
