# Generated by Django 5.2.4 on 2025-08-24 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_costo', '0001_initial'),
        ('transacciones', '0002_tipotransaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocontable',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='centros_costo.centrocosto', verbose_name='Centro de Costo'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='centros_costo.proyecto', verbose_name='Proyecto'),
        ),
    ]
