# Generated by Django 4.2.7 on 2025-08-24 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(max_length=100, verbose_name="Modelo afectado"),
                ),
                ("registro_id", models.IntegerField(verbose_name="ID del registro")),
                (
                    "campo",
                    models.CharField(max_length=100, verbose_name="Campo modificado"),
                ),
                (
                    "valor_anterior",
                    models.TextField(blank=True, verbose_name="Valor anterior"),
                ),
                (
                    "valor_nuevo",
                    models.TextField(blank=True, verbose_name="Valor nuevo"),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del cambio"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que realizó el cambio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Cambio",
                "verbose_name_plural": "Logs de Cambios",
                "ordering": ["-fecha_cambio"],
                "indexes": [
                    models.Index(
                        fields=["modelo", "registro_id"],
                        name="core_logcam_modelo_9fc5f6_idx",
                    ),
                    models.Index(
                        fields=["usuario", "fecha_cambio"],
                        name="core_logcam_usuario_dce834_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete: False indica registro eliminado",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Versión del registro"),
                ),
                (
                    "clave",
                    models.CharField(
                        max_length=100, verbose_name="Clave de configuración"
                    ),
                ),
                ("valor", models.JSONField(verbose_name="Valor de configuración")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SISTEMA", "Sistema"),
                            ("CONTABILIDAD", "Contabilidad"),
                            ("FISCAL", "Fiscal"),
                            ("REPORTES", "Reportes"),
                        ],
                        default="SISTEMA",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuraciones",
                "unique_together": {("empresa", "clave")},
            },
        ),
    ]
