# Generated by Django 5.2.4 on 2025-08-24 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('empresas', '0003_auto_20250824_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SISTEMA', 'Sistema'), ('CONTABILIDAD', 'Contabilidad'), ('FISCAL', 'Fiscal'), ('REPORTES', 'Reportes')], default='SISTEMA', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('moneda_principal', models.CharField(default='MXN', help_text='Código ISO de 3 letras (ej: MXN, USD, EUR)', max_length=3, verbose_name='Moneda principal')),
                ('simbolo_moneda', models.CharField(default='$', max_length=5, verbose_name='Símbolo de moneda')),
                ('decimales_moneda', models.IntegerField(default=2, verbose_name='Decimales en moneda')),
                ('formato_fecha', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD-MM-YYYY', 'DD-MM-YYYY')], default='DD/MM/YYYY', max_length=20, verbose_name='Formato de fecha')),
                ('separador_miles', models.CharField(choices=[(',', 'Coma (,)'), ('.', 'Punto (.)'), (' ', 'Espacio ( )')], default=',', max_length=1, verbose_name='Separador de miles')),
                ('separador_decimal', models.CharField(choices=[('.', 'Punto (.)'), (',', 'Coma (,)')], default='.', max_length=1, verbose_name='Separador decimal')),
                ('zona_horaria', models.CharField(default='America/Mexico_City', help_text='Zona horaria de la empresa', max_length=50, verbose_name='Zona horaria')),
                ('notificaciones_email', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('notificaciones_sistema', models.BooleanField(default=True, verbose_name='Notificaciones del sistema')),
                ('email_notificaciones', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para notificaciones')),
                ('tema_interfaz', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=20, verbose_name='Tema de la interfaz')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5, verbose_name='Idioma')),
                ('inicio_ejercicio_fiscal', models.CharField(default='01-01', help_text='Formato MM-DD (ej: 01-01 para enero 1)', max_length=5, verbose_name='Inicio ejercicio fiscal')),
                ('fin_ejercicio_fiscal', models.CharField(default='12-31', help_text='Formato MM-DD (ej: 12-31 para diciembre 31)', max_length=5, verbose_name='Fin ejercicio fiscal')),
                ('backup_automatico', models.BooleanField(default=True, verbose_name='Backup automático')),
                ('frecuencia_backup', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', max_length=20, verbose_name='Frecuencia de backup')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_general', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuraciones Generales',
            },
        ),
    ]
