# Generated by Django 5.2.4 on 2025-08-24 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_auto_20250824_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('codigo', models.CharField(help_text='Código único del centro de costo', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('DEPARTAMENTO', 'Departamento'), ('SUCURSAL', 'Sucursal'), ('ACTIVIDAD', 'Actividad'), ('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], default='DEPARTAMENTO', max_length=20, verbose_name='Tipo')),
                ('permite_movimientos', models.BooleanField(default=True, help_text='Si permite asignar movimientos contables directamente', verbose_name='Permite movimientos')),
                ('color_interfaz', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Morado'), ('red', 'Rojo'), ('yellow', 'Amarillo'), ('indigo', 'Índigo'), ('pink', 'Rosa'), ('gray', 'Gris')], default='blue', max_length=20, verbose_name='Color en interfaz')),
                ('centro_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcentros', to='centros_costo.centrocosto', verbose_name='Centro Padre')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_costo', to='empresas.empresa', verbose_name='Empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('codigo', models.CharField(help_text='Código único del proyecto', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha fin estimada')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha fin real')),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='PLANIFICACION', max_length=20, verbose_name='Estado')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presupuesto')),
                ('color_interfaz', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Morado'), ('red', 'Rojo'), ('yellow', 'Amarillo'), ('indigo', 'Índigo'), ('pink', 'Rosa'), ('gray', 'Gris')], default='green', max_length=20, verbose_name='Color en interfaz')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='centros_costo.centrocosto', verbose_name='Centro de Costo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='empresas.empresa', verbose_name='Empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
