# Generated by Django 5.2.5 on 2025-08-24 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_costo', '0001_initial'),
        ('empresas', '0003_auto_20250824_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('codigo', models.CharField(help_text='Código único del tipo', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color_interfaz', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarillo'), ('red', 'Rojo'), ('purple', 'Morado'), ('indigo', 'Índigo'), ('gray', 'Gris')], default='blue', max_length=20, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_centro_costo', to='empresas.empresa', verbose_name='Empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de Centro',
                'verbose_name_plural': 'Tipos de Centro',
                'ordering': ['orden', 'codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='tipo_nuevo',
            field=models.ForeignKey(blank=True, help_text='Nuevo campo de tipo de centro de costo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros', to='centros_costo.tipocentrocosto', verbose_name='Tipo Nuevo'),
        ),
    ]
