# Generated by Django 4.2.7 on 2025-08-26 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_auto_20250824_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDIDownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('tipo_cfdi', models.CharField(choices=[('RECIBIDOS', 'CFDI Recibidos'), ('EMITIDOS', 'CFDI Emitidos'), ('TODOS', 'Todos los CFDI')], default='RECIBIDOS', max_length=20, verbose_name='Tipo de CFDI')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('solicitud_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de solicitud SAT')),
                ('total_cfdi', models.IntegerField(default=0, verbose_name='Total de CFDI')),
                ('procesados', models.IntegerField(default=0, verbose_name='CFDI procesados')),
                ('archivo_descarga', models.FileField(blank=True, null=True, upload_to='cfdi_downloads/', verbose_name='Archivo de descarga')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('fecha_inicio_proceso', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del proceso')),
                ('fecha_fin_proceso', models.DateTimeField(blank=True, null=True, verbose_name='Fin del proceso')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_descarga_cfdi', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Trabajo de Descarga CFDI',
                'verbose_name_plural': 'Trabajos de Descarga CFDI',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID/Folio Fiscal')),
                ('serie', models.CharField(blank=True, max_length=25, verbose_name='Serie')),
                ('folio', models.CharField(blank=True, max_length=40, verbose_name='Folio')),
                ('fecha_emision', models.DateTimeField(verbose_name='Fecha de emisión')),
                ('fecha_certificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de certificación')),
                ('rfc_emisor', models.CharField(max_length=13, verbose_name='RFC Emisor')),
                ('nombre_emisor', models.CharField(max_length=254, verbose_name='Nombre Emisor')),
                ('rfc_receptor', models.CharField(max_length=13, verbose_name='RFC Receptor')),
                ('nombre_receptor', models.CharField(max_length=254, verbose_name='Nombre Receptor')),
                ('tipo_comprobante', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRASLADO', 'Traslado'), ('NOMINA', 'Nómina'), ('PAGO', 'Pago')], max_length=20, verbose_name='Tipo de comprobante')),
                ('estado_sat', models.CharField(choices=[('VIGENTE', 'Vigente'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente de validación')], default='PENDIENTE', max_length=20, verbose_name='Estado en SAT')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('moneda', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='cfdi_xml/', verbose_name='Archivo XML')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cfdi_pdf/', verbose_name='Archivo PDF')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('validado_sat', models.BooleanField(default=False, verbose_name='Validado en SAT')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfdi_registros', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('trabajo_descarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfdi_descargados', to='sat_integration.cfdidownloadjob')),
            ],
            options={
                'verbose_name': 'CFDI',
                'verbose_name_plural': 'CFDIs',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='SATCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('certificado_cer', models.FileField(upload_to='sat_credentials/cer/', verbose_name='Archivo .cer')),
                ('llave_privada_key', models.FileField(upload_to='sat_credentials/key/', verbose_name='Archivo .key')),
                ('password_llave', models.CharField(help_text='Se almacena encriptada', max_length=255, verbose_name='Contraseña de llave privada')),
                ('validadas', models.BooleanField(default=False, verbose_name='Credenciales validadas')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento del certificado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales_sat', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Credenciales SAT',
                'verbose_name_plural': 'Credenciales SAT',
            },
        ),
        migrations.CreateModel(
            name='CFDIStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Soft delete: False indica registro eliminado', verbose_name='Activo')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del registro')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('fecha_consulta', models.DateTimeField(verbose_name='Fecha de consulta al SAT')),
                ('respuesta_sat', models.JSONField(blank=True, null=True, verbose_name='Respuesta completa del SAT')),
                ('cfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_estado', to='sat_integration.cfdi')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Log de Estado CFDI',
                'verbose_name_plural': 'Logs de Estado CFDI',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='cfdi',
            index=models.Index(fields=['uuid'], name='sat_integrat_uuid_6c3b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdi',
            index=models.Index(fields=['rfc_emisor', 'fecha_emision'], name='sat_integrat_rfc_emi_7e2baf_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdi',
            index=models.Index(fields=['rfc_receptor', 'fecha_emision'], name='sat_integrat_rfc_rec_6ee23e_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdi',
            index=models.Index(fields=['empresa', 'estado_sat'], name='sat_integrat_empresa_c87cc4_idx'),
        ),
    ]
