# Generated by Django 4.2.7 on 2025-08-24 06:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0002_alter_empresa_options_empresa_limite_usuarios_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete: False indica registro eliminado",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Versión del registro"),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Código debe ser numérico con separadores - o .",
                                regex="^[0-9]+([-\\.][0-9]+)*$",
                            )
                        ],
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Cuenta"
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        help_text="1=Mayor, 2=Subcuenta, 3=Sub-subcuenta",
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PASIVO", "Pasivo"),
                            ("CAPITAL", "Capital"),
                            ("INGRESO", "Ingreso"),
                            ("COSTO", "Costo"),
                            ("GASTO", "Gasto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[("DEUDORA", "Deudora"), ("ACREEDORA", "Acreedora")],
                        max_length=10,
                        verbose_name="Naturaleza",
                    ),
                ),
                (
                    "afectable",
                    models.BooleanField(
                        default=True,
                        help_text="Si puede recibir movimientos contables",
                        verbose_name="Afectable",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "cuenta_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcuentas",
                        to="catalogo_cuentas.cuentacontable",
                        verbose_name="Cuenta Padre",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_contables",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Cuentas Contables",
                "ordering": ["codigo"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
    ]
